export enum FrameworkEnum {
  React = 'React',
  jQuery = 'jQuery',
  Express = 'Express',
  NestJS = 'NestJS',
  Angular = 'Angular',
  Vue = 'Vue',
  ASPNET = 'ASP.NET',
  Flask = 'Flask',
  Django = 'Django',
  Spring = 'Spring',
  Laravel = 'Laravel',
  RubyOnRails = 'Ruby on Rails',
  Gatsby = 'Gatsby',
  FastAPI = 'FastAPI',
  Symfony = 'Symfony',
  Svelte = 'Svelte',
  Drupal = 'Drupal',
}
