export enum ProgrammingLanguageEnum {
  JavaScript = 'JavaScript',
  Python = 'Python',
  Java = 'Java',
  PHP = 'PHP',
  CSH = 'C#',
  CPP = 'C++',
  CSS = 'CSS',
  TypeScript = 'TypeScript',
  Ruby = 'Ruby',
  C = 'C',
  Swift = 'Swift',
  R = 'R',
  ObjectiveC = 'Objective-C',
  Shell = 'Shell',
  Scala = 'Scala',
  Go = 'Go',
  PowerShell = 'PowerShell',
  Kotlin = 'Kotlin',
  Rust = 'Rust',
  Perl = 'Perl',
}
